# Suicide Data Analysis

In [2]:
import numpy as np

In [3]:
a=np.genfromtxt('/home/kunalverma/Itronix Solutions/dummy/Suicidesindia2001-2012.csv',delimiter=',', dtype=str)
print(a)
print(len(a))

[['State' 'Year' 'Type_code' ... 'Gender' 'Age_group' 'Total']
 ['A & N Islands' '2001' 'Causes' ... 'Female' '0-14' '0']
 ['A & N Islands' '2001' 'Causes' ... 'Female' '0-14' '0']
 ...
 ['West Bengal' '2012' 'Social_Status' ... 'Male' '0-100+' '5451']
 ['West Bengal' '2012' 'Social_Status' ... 'Male' '0-100+' '189']
 ['West Bengal' '2012' 'Social_Status' ... 'Male' '0-100+' '2658']]
237520

In [4]:
print(a.shape)

(237520, 7)

In [5]:
suicides=np.array(a[1:,6], dtype=int)
print("Total Suicides in India : ",np.sum(suicides))

Total Suicides in India :  13071734

## Statewise- YearWise Analysis

In [65]:


"""pd=np.where(a[...,0]=="Punjab")
print(a[pd])
print()
year=np.where(np.logical_and(a[...,0]=="Punjab",a[...,1]=="2008"))
print(a[year])"""
states=np.array(a[1:,...],dtype=str)

def findsuicides(state,year):
    data=states[states[:,0]==state]
    deaths=np.array(data[:,6],dtype=int)
    b=np.where(data[:,1]==year)
    #numberofDeaths=np.array(b[:,6] , dtype=int)
    print("Total Suicides in ",state," in ",year," are ",np.sum(deaths[b]))

In [66]:
s=np.array(a[1:,0])
y=input("Enter Year : ")
statesset=set(s)
stateslist=[value for value in statesset]
stateslist.sort()
for i in stateslist:
    findsuicides(i,y)

Enter Year : 2001
Total Suicides in  A & N Islands  in  2001  are  645
Total Suicides in  Andhra Pradesh  in  2001  are  52610
Total Suicides in  Arunachal Pradesh  in  2001  are  555
Total Suicides in  Assam  in  2001  are  13230
Total Suicides in  Bihar  in  2001  are  3015
Total Suicides in  Chandigarh  in  2001  are  350
Total Suicides in  Chhattisgarh  in  2001  are  20051
Total Suicides in  D & N Haveli  in  2001  are  250
Total Suicides in  Daman & Diu  in  2001  are  69
Total Suicides in  Delhi (Ut)  in  2001  are  6195
Total Suicides in  Goa  in  2001  are  1280
Total Suicides in  Gujarat  in  2001  are  23955
Total Suicides in  Haryana  in  2001  are  10031
Total Suicides in  Himachal Pradesh  in  2001  are  1535
Total Suicides in  Jammu & Kashmir  in  2001  are  765
Total Suicides in  Jharkhand  in  2001  are  1250
Total Suicides in  Karnataka  in  2001  are  59405
Total Suicides in  Kerala  in  2001  are  47860
Total Suicides in  Lakshadweep  in  2001  are  0
Total Suicides in  Madhya Pradesh  in  2001  are  34300
Total Suicides in  Maharashtra  in  2001  are  73090
Total Suicides in  Manipur  in  2001  are  205
Total Suicides in  Meghalaya  in  2001  are  435
Total Suicides in  Mizoram  in  2001  are  270
Total Suicides in  Nagaland  in  2001  are  200
Total Suicides in  Odisha  in  2001  are  20254
Total Suicides in  Puducherry  in  2001  are  2645
Total Suicides in  Punjab  in  2001  are  3240
Total Suicides in  Rajasthan  in  2001  are  15975
Total Suicides in  Sikkim  in  2001  are  470
Total Suicides in  Tamil Nadu  in  2001  are  56450
Total Suicides in  Total (All India)  in  2001  are  217012
Total Suicides in  Total (States)  in  2001  are  212950
Total Suicides in  Total (Uts)  in  2001  are  4062
Total Suicides in  Tripura  in  2001  are  4270
Total Suicides in  Uttar Pradesh  in  2001  are  17580
Total Suicides in  Uttarakhand  in  2001  are  1555
Total Suicides in  West Bengal  in  2001  are  68450

### Statewise - Analysis

In [67]:
def find(state):
    data=states[states[:,0]==state]
    deaths=np.array(data[:,6],dtype=int)
    print("Total Suicides in {} are {}".format(state,np.sum(deaths)))

In [68]:
for i in stateslist:
    find(i)

Total Suicides in A & N Islands are 8109
Total Suicides in Andhra Pradesh are 814059
Total Suicides in Arunachal Pradesh are 6633
Total Suicides in Assam are 172276
Total Suicides in Bihar are 46214
Total Suicides in Chandigarh are 5164
Total Suicides in Chhattisgarh are 302354
Total Suicides in D & N Haveli are 3430
Total Suicides in Daman & Diu are 1391
Total Suicides in Delhi (Ut) are 84272
Total Suicides in Goa are 17363
Total Suicides in Gujarat are 330858
Total Suicides in Haryana are 147176
Total Suicides in Himachal Pradesh are 26562
Total Suicides in Jammu & Kashmir are 14821
Total Suicides in Jharkhand are 49720
Total Suicides in Karnataka are 734825
Total Suicides in Kerala are 538946
Total Suicides in Lakshadweep are 50
Total Suicides in Madhya Pradesh are 451535
Total Suicides in Maharashtra are 901945
Total Suicides in Manipur are 2102
Total Suicides in Meghalaya are 5415
Total Suicides in Mizoram are 4154
Total Suicides in Nagaland are 1728
Total Suicides in Odisha are 267234
Total Suicides in Puducherry are 32144
Total Suicides in Punjab are 46350
Total Suicides in Rajasthan are 255134
Total Suicides in Sikkim are 9606
Total Suicides in Tamil Nadu are 818691
Total Suicides in Total (All India) are 2911862
Total Suicides in Total (States) are 2858026
Total Suicides in Total (Uts) are 53836
Total Suicides in Tripura are 45965
Total Suicides in Uttar Pradesh are 233352
Total Suicides in Uttarakhand are 18496
Total Suicides in West Bengal are 849936

## YearWise Analysis

In [69]:
def yearwise(y):
    year=np.array(a[np.where(a[:,1]==y)])
    deaths=np.array(year[:,6],dtype=int)
    print("Suicides in the Year ",y," ", np.sum(deaths))

In [72]:
year =np.array(a[1:,1])

yearset=set(year)
yearlist=[value for value in yearset]
yearlist.sort()
#print(yearset)

for i in yearlist:
        yearwise(i)

Suicides in the Year  2001   976464
Suicides in the Year  2002   993648
Suicides in the Year  2003   997622
Suicides in the Year  2004   1023137
Suicides in the Year  2005   1025201
Suicides in the Year  2006   1062991
Suicides in the Year  2007   1103667
Suicides in the Year  2008   1125082
Suicides in the Year  2009   1144033
Suicides in the Year  2010   1211322
Suicides in the Year  2011   1219499
Suicides in the Year  2012   1189068

## GenderWise Analysis

In [112]:
female=a[a[:,4]=="Female"]
male=a[a[:,4]=="Male"]
male_commit_suicide=np.array(male[:,6],dtype=int)
female_commit_suicide=np.array(female[:,6],dtype=int)
print("Male Suicide Count is {} and Female Suicide Count is {}".format(np.sum(male_commit_suicide),np.sum(female_commit_suicide)))

Male Suicide Count is 8368760 and Female Suicide Count is 4702974

#### Statewise - Gender Wise analysis

In [149]:
def stategender(state):
    m=np.where(np.logical_and(a[...,4]=="Male",a[...,0]==state))
    male=a[m]
    male_commit_suicide=np.array(male[...,6],dtype=int)
    m=np.where(np.logical_and(a[...,4]=="Female",a[...,0]==state))
    female=a[m]
    female_commit_suicide=np.array(female[...,6],dtype=int)
    
    print("In {} \nMale Suicide : {} \tFemale Suicide :{}".format(state,np.sum(male_commit_suicide),np.sum(female_commit_suicide)))

In [155]:
for i in stateslist:
    stategender(i)

In A & N Islands
Male Suicide : 5359 	Female Suicide :2750
In Andhra Pradesh
Male Suicide : 542120 	Female Suicide :271939
In Arunachal Pradesh
Male Suicide : 4679 	Female Suicide :1954
In Assam
Male Suicide : 117152 	Female Suicide :55124
In Bihar
Male Suicide : 25960 	Female Suicide :20254
In Chandigarh
Male Suicide : 3277 	Female Suicide :1887
In Chhattisgarh
Male Suicide : 203780 	Female Suicide :98574
In D & N Haveli
Male Suicide : 2030 	Female Suicide :1400
In Daman & Diu
Male Suicide : 916 	Female Suicide :475
In Delhi (Ut)
Male Suicide : 53594 	Female Suicide :30678
In Goa
Male Suicide : 11841 	Female Suicide :5522
In Gujarat
Male Suicide : 198365 	Female Suicide :132493
In Haryana
Male Suicide : 108070 	Female Suicide :39106
In Himachal Pradesh
Male Suicide : 16921 	Female Suicide :9641
In Jammu & Kashmir
Male Suicide : 8016 	Female Suicide :6805
In Jharkhand
Male Suicide : 32038 	Female Suicide :17682
In Karnataka
Male Suicide : 491955 	Female Suicide :242870
In Kerala
Male Suicide : 393793 	Female Suicide :145153
In Lakshadweep
Male Suicide : 20 	Female Suicide :30
In Madhya Pradesh
Male Suicide : 248385 	Female Suicide :203150
In Maharashtra
Male Suicide : 608770 	Female Suicide :293175
In Manipur
Male Suicide : 1438 	Female Suicide :664
In Meghalaya
Male Suicide : 3857 	Female Suicide :1558
In Mizoram
Male Suicide : 3599 	Female Suicide :555
In Nagaland
Male Suicide : 1295 	Female Suicide :433
In Odisha
Male Suicide : 157629 	Female Suicide :109605
In Puducherry
Male Suicide : 21140 	Female Suicide :11004
In Punjab
Male Suicide : 35375 	Female Suicide :10975
In Rajasthan
Male Suicide : 172845 	Female Suicide :82289
In Sikkim
Male Suicide : 6287 	Female Suicide :3319
In Tamil Nadu
Male Suicide : 512206 	Female Suicide :306485
In Total (All India)
Male Suicide : 1863836 	Female Suicide :1048026
In Total (States)
Male Suicide : 1829296 	Female Suicide :1028730
In Total (Uts)
Male Suicide : 34540 	Female Suicide :19296
In Tripura
Male Suicide : 27406 	Female Suicide :18559
In Uttar Pradesh
Male Suicide : 125327 	Female Suicide :108025
In Uttarakhand
Male Suicide : 10948 	Female Suicide :7548
In West Bengal
Male Suicide : 484695 	Female Suicide :365241

#### Genderwise -YearWise analysis

In [161]:
def yeargender(year):
    y=np.where(np.logical_and(a[...,4]=="Male",a[...,1]==year))
    male=a[y]
    male_commit_suicide=np.array(male[...,6],dtype=int)
    y=np.where(np.logical_and(a[...,4]=="Female",a[...,1]==year))
    female=a[y]
    female_commit_suicide=np.array(female[...,6],dtype=int)
    
    print("In {} \nMale Suicide : {} \tFemale Suicide :{}".format(year,np.sum(male_commit_suicide),np.sum(female_commit_suicide)))

In [162]:
for i in yearlist:
    yeargender(i)

In 2001
Male Suicide : 596819 	Female Suicide :379645
In 2002
Male Suicide : 623973 	Female Suicide :369675
In 2003
Male Suicide : 631965 	Female Suicide :365657
In 2004
Male Suicide : 653840 	Female Suicide :369297
In 2005
Male Suicide : 656221 	Female Suicide :368980
In 2006
Male Suicide : 681314 	Female Suicide :381677
In 2007
Male Suicide : 713635 	Female Suicide :390032
In 2008
Male Suicide : 724880 	Female Suicide :400202
In 2009
Male Suicide : 732983 	Female Suicide :411050
In 2010
Male Suicide : 784617 	Female Suicide :426705
In 2011
Male Suicide : 789811 	Female Suicide :429688
In 2012
Male Suicide : 778702 	Female Suicide :410366

#### Statewise-yearwise-genderwise analysis

In [169]:
def stateyeargender(state,year):
    temp=np.where(np.logical_and(np.logical_and(a[...,0]==state,a[...,1]==year),a[...,4]=="Male"))
    male=a[temp]
    male_commit_suicide=np.array(male[...,6],dtype=int)
    temp=np.where(np.logical_and(np.logical_and(a[...,0]==state,a[...,1]==year),a[...,4]=="Female"))
    female=a[temp]
    female_commit_suicide=np.array(female[...,6],dtype=int)
    
    print("In {} \nMale Suicide : {} \tFemale Suicide : {}".format(year,np.sum(male_commit_suicide),np.sum(female_commit_suicide)))

In [175]:
for i in stateslist:
    print("In {}".format(i))
    print()
    for j in yearlist:
        stateyeargender(i,j)
    print()
    print()

In A & N Islands

In 2001
Male Suicide : 395 	Female Suicide : 250
In 2002
Male Suicide : 455 	Female Suicide : 265
In 2003
Male Suicide : 350 	Female Suicide : 215
In 2004
Male Suicide : 405 	Female Suicide : 205
In 2005
Male Suicide : 430 	Female Suicide : 265
In 2006
Male Suicide : 480 	Female Suicide : 185
In 2007
Male Suicide : 495 	Female Suicide : 280
In 2008
Male Suicide : 489 	Female Suicide : 225
In 2009
Male Suicide : 430 	Female Suicide : 225
In 2010
Male Suicide : 560 	Female Suicide : 220
In 2011
Male Suicide : 470 	Female Suicide : 210
In 2012
Male Suicide : 400 	Female Suicide : 205


In Andhra Pradesh

In 2001
Male Suicide : 31895 	Female Suicide : 20715
In 2002
Male Suicide : 37855 	Female Suicide : 20610
In 2003
Male Suicide : 37565 	Female Suicide : 19480
In 2004
Male Suicide : 45410 	Female Suicide : 22220
In 2005
Male Suicide : 44325 	Female Suicide : 22885
In 2006
Male Suicide : 44315 	Female Suicide : 22065
In 2007
Male Suicide : 49745 	Female Suicide : 24665
In 2008
Male Suicide : 48605 	Female Suicide : 23124
In 2009
Male Suicide : 49435 	Female Suicide : 23065
In 2010
Male Suicide : 54735 	Female Suicide : 24770
In 2011
Male Suicide : 50600 	Female Suicide : 24785
In 2012
Male Suicide : 47635 	Female Suicide : 23555


In Arunachal Pradesh

In 2001
Male Suicide : 380 	Female Suicide : 175
In 2002
Male Suicide : 355 	Female Suicide : 215
In 2003
Male Suicide : 270 	Female Suicide : 135
In 2004
Male Suicide : 245 	Female Suicide : 150
In 2005
Male Suicide : 245 	Female Suicide : 105
In 2006
Male Suicide : 480 	Female Suicide : 165
In 2007
Male Suicide : 490 	Female Suicide : 154
In 2008
Male Suicide : 384 	Female Suicide : 165
In 2009
Male Suicide : 384 	Female Suicide : 165
In 2010
Male Suicide : 455 	Female Suicide : 200
In 2011
Male Suicide : 495 	Female Suicide : 175
In 2012
Male Suicide : 496 	Female Suicide : 150


In Assam

In 2001
Male Suicide : 9180 	Female Suicide : 4050
In 2002
Male Suicide : 8510 	Female Suicide : 4040
In 2003
Male Suicide : 8363 	Female Suicide : 4600
In 2004
Male Suicide : 9725 	Female Suicide : 4453
In 2005
Male Suicide : 9734 	Female Suicide : 4475
In 2006
Male Suicide : 10580 	Female Suicide : 4575
In 2007
Male Suicide : 10580 	Female Suicide : 4721
In 2008
Male Suicide : 9850 	Female Suicide : 5095
In 2009
Male Suicide : 9410 	Female Suicide : 5420
In 2010
Male Suicide : 10130 	Female Suicide : 4835
In 2011
Male Suicide : 9130 	Female Suicide : 4500
In 2012
Male Suicide : 11960 	Female Suicide : 4360


In Bihar

In 2001
Male Suicide : 1535 	Female Suicide : 1480
In 2002
Male Suicide : 2130 	Female Suicide : 1470
In 2003
Male Suicide : 1755 	Female Suicide : 1229
In 2004
Male Suicide : 1060 	Female Suicide : 695
In 2005
Male Suicide : 1635 	Female Suicide : 1080
In 2006
Male Suicide : 1495 	Female Suicide : 1595
In 2007
Male Suicide : 2670 	Female Suicide : 2155
In 2008
Male Suicide : 3045 	Female Suicide : 2030
In 2009
Male Suicide : 2570 	Female Suicide : 2685
In 2010
Male Suicide : 3560 	Female Suicide : 2570
In 2011
Male Suicide : 2230 	Female Suicide : 1745
In 2012
Male Suicide : 2275 	Female Suicide : 1520


In Chandigarh

In 2001
Male Suicide : 195 	Female Suicide : 155
In 2002
Male Suicide : 265 	Female Suicide : 170
In 2003
Male Suicide : 340 	Female Suicide : 175
In 2004
Male Suicide : 260 	Female Suicide : 115
In 2005
Male Suicide : 315 	Female Suicide : 130
In 2006
Male Suicide : 280 	Female Suicide : 120
In 2007
Male Suicide : 298 	Female Suicide : 110
In 2008
Male Suicide : 290 	Female Suicide : 125
In 2009
Male Suicide : 219 	Female Suicide : 155
In 2010
Male Suicide : 155 	Female Suicide : 200
In 2011
Male Suicide : 285 	Female Suicide : 240
In 2012
Male Suicide : 375 	Female Suicide : 192


In Chhattisgarh

In 2001
Male Suicide : 13200 	Female Suicide : 6851
In 2002
Male Suicide : 13145 	Female Suicide : 6605
In 2003
Male Suicide : 12960 	Female Suicide : 6635
In 2004
Male Suicide : 14930 	Female Suicide : 7545
In 2005
Male Suicide : 16525 	Female Suicide : 7880
In 2006
Male Suicide : 15300 	Female Suicide : 7830
In 2007
Male Suicide : 16280 	Female Suicide : 7915
In 2008
Male Suicide : 16240 	Female Suicide : 8485
In 2009
Male Suicide : 19770 	Female Suicide : 9645
In 2010
Male Suicide : 22725 	Female Suicide : 9838
In 2011
Male Suicide : 22635 	Female Suicide : 11145
In 2012
Male Suicide : 20070 	Female Suicide : 8200


In D & N Haveli

In 2001
Male Suicide : 175 	Female Suicide : 75
In 2002
Male Suicide : 160 	Female Suicide : 90
In 2003
Male Suicide : 150 	Female Suicide : 110
In 2004
Male Suicide : 100 	Female Suicide : 95
In 2005
Male Suicide : 205 	Female Suicide : 140
In 2006
Male Suicide : 115 	Female Suicide : 95
In 2007
Male Suicide : 220 	Female Suicide : 160
In 2008
Male Suicide : 160 	Female Suicide : 140
In 2009
Male Suicide : 150 	Female Suicide : 130
In 2010
Male Suicide : 185 	Female Suicide : 130
In 2011
Male Suicide : 205 	Female Suicide : 110
In 2012
Male Suicide : 205 	Female Suicide : 125


In Daman & Diu

In 2001
Male Suicide : 49 	Female Suicide : 20
In 2002
Male Suicide : 75 	Female Suicide : 10
In 2003
Male Suicide : 88 	Female Suicide : 30
In 2004
Male Suicide : 25 	Female Suicide : 40
In 2005
Male Suicide : 124 	Female Suicide : 35
In 2006
Male Suicide : 70 	Female Suicide : 40
In 2007
Male Suicide : 30 	Female Suicide : 45
In 2008
Male Suicide : 70 	Female Suicide : 25
In 2009
Male Suicide : 75 	Female Suicide : 40
In 2010
Male Suicide : 95 	Female Suicide : 60
In 2011
Male Suicide : 90 	Female Suicide : 75
In 2012
Male Suicide : 125 	Female Suicide : 55


In Delhi (Ut)

In 2001
Male Suicide : 3650 	Female Suicide : 2545
In 2002
Male Suicide : 3215 	Female Suicide : 2050
In 2003
Male Suicide : 3705 	Female Suicide : 2060
In 2004
Male Suicide : 3994 	Female Suicide : 2283
In 2005
Male Suicide : 3885 	Female Suicide : 2339
In 2006
Male Suicide : 4800 	Female Suicide : 2658
In 2007
Male Suicide : 4830 	Female Suicide : 2575
In 2008
Male Suicide : 3975 	Female Suicide : 2536
In 2009
Male Suicide : 4665 	Female Suicide : 2720
In 2010
Male Suicide : 4805 	Female Suicide : 2908
In 2011
Male Suicide : 5840 	Female Suicide : 2740
In 2012
Male Suicide : 6230 	Female Suicide : 3264


In Goa

In 2001
Male Suicide : 835 	Female Suicide : 445
In 2002
Male Suicide : 1130 	Female Suicide : 415
In 2003
Male Suicide : 1065 	Female Suicide : 435
In 2004
Male Suicide : 1060 	Female Suicide : 510
In 2005
Male Suicide : 985 	Female Suicide : 425
In 2006
Male Suicide : 915 	Female Suicide : 460
In 2007
Male Suicide : 890 	Female Suicide : 460
In 2008
Male Suicide : 911 	Female Suicide : 520
In 2009
Male Suicide : 915 	Female Suicide : 467
In 2010
Male Suicide : 1180 	Female Suicide : 430
In 2011
Male Suicide : 975 	Female Suicide : 490
In 2012
Male Suicide : 980 	Female Suicide : 465


In Gujarat

In 2001
Male Suicide : 13245 	Female Suicide : 10710
In 2002
Male Suicide : 13530 	Female Suicide : 9686
In 2003
Male Suicide : 13250 	Female Suicide : 9580
In 2004
Male Suicide : 14250 	Female Suicide : 9618
In 2005
Male Suicide : 14510 	Female Suicide : 9315
In 2006
Male Suicide : 15240 	Female Suicide : 9932
In 2007
Male Suicide : 16875 	Female Suicide : 11025
In 2008
Male Suicide : 18675 	Female Suicide : 12143
In 2009
Male Suicide : 18355 	Female Suicide : 12424
In 2010
Male Suicide : 19065 	Female Suicide : 11970
In 2011
Male Suicide : 19560 	Female Suicide : 12350
In 2012
Male Suicide : 21810 	Female Suicide : 13740


In Haryana

In 2001
Male Suicide : 6820 	Female Suicide : 3211
In 2002
Male Suicide : 7850 	Female Suicide : 3150
In 2003
Male Suicide : 8065 	Female Suicide : 3070
In 2004
Male Suicide : 7270 	Female Suicide : 3140
In 2005
Male Suicide : 7465 	Female Suicide : 2765
In 2006
Male Suicide : 8830 	Female Suicide : 2750
In 2007
Male Suicide : 9260 	Female Suicide : 2905
In 2008
Male Suicide : 9870 	Female Suicide : 3410
In 2009
Male Suicide : 9075 	Female Suicide : 3440
In 2010
Male Suicide : 10890 	Female Suicide : 3580
In 2011
Male Suicide : 12320 	Female Suicide : 3905
In 2012
Male Suicide : 10355 	Female Suicide : 3780


In Himachal Pradesh

In 2001
Male Suicide : 885 	Female Suicide : 650
In 2002
Male Suicide : 1040 	Female Suicide : 630
In 2003
Male Suicide : 1196 	Female Suicide : 730
In 2004
Male Suicide : 1165 	Female Suicide : 675
In 2005
Male Suicide : 1070 	Female Suicide : 725
In 2006
Male Suicide : 1505 	Female Suicide : 780
In 2007
Male Suicide : 1290 	Female Suicide : 720
In 2008
Male Suicide : 2085 	Female Suicide : 1063
In 2009
Male Suicide : 1830 	Female Suicide : 970
In 2010
Male Suicide : 1740 	Female Suicide : 963
In 2011
Male Suicide : 1345 	Female Suicide : 869
In 2012
Male Suicide : 1770 	Female Suicide : 866


In Jammu & Kashmir

In 2001
Male Suicide : 455 	Female Suicide : 310
In 2002
Male Suicide : 479 	Female Suicide : 440
In 2003
Male Suicide : 315 	Female Suicide : 375
In 2004
Male Suicide : 255 	Female Suicide : 305
In 2005
Male Suicide : 980 	Female Suicide : 490
In 2006
Male Suicide : 759 	Female Suicide : 542
In 2007
Male Suicide : 765 	Female Suicide : 405
In 2008
Male Suicide : 882 	Female Suicide : 665
In 2009
Male Suicide : 837 	Female Suicide : 765
In 2010
Male Suicide : 610 	Female Suicide : 685
In 2011
Male Suicide : 719 	Female Suicide : 713
In 2012
Male Suicide : 960 	Female Suicide : 1110


In Jharkhand

In 2001
Male Suicide : 705 	Female Suicide : 545
In 2002
Male Suicide : 765 	Female Suicide : 595
In 2003
Male Suicide : 765 	Female Suicide : 595
In 2004
Male Suicide : 1165 	Female Suicide : 920
In 2005
Male Suicide : 2615 	Female Suicide : 1425
In 2006
Male Suicide : 2605 	Female Suicide : 1675
In 2007
Male Suicide : 4400 	Female Suicide : 2027
In 2008
Male Suicide : 3010 	Female Suicide : 1545
In 2009
Male Suicide : 3720 	Female Suicide : 1830
In 2010
Male Suicide : 3973 	Female Suicide : 2185
In 2011
Male Suicide : 4125 	Female Suicide : 1935
In 2012
Male Suicide : 4190 	Female Suicide : 2405


In Karnataka

In 2001
Male Suicide : 39355 	Female Suicide : 20050
In 2002
Male Suicide : 40400 	Female Suicide : 20950
In 2003
Male Suicide : 41875 	Female Suicide : 19930
In 2004
Male Suicide : 40090 	Female Suicide : 19595
In 2005
Male Suicide : 38535 	Female Suicide : 19250
In 2006
Male Suicide : 40240 	Female Suicide : 20820
In 2007
Male Suicide : 41960 	Female Suicide : 19560
In 2008
Male Suicide : 41080 	Female Suicide : 20030
In 2009
Male Suicide : 41045 	Female Suicide : 19930
In 2010
Male Suicide : 42035 	Female Suicide : 21220
In 2011
Male Suicide : 42360 	Female Suicide : 20750
In 2012
Male Suicide : 42980 	Female Suicide : 20785


In Kerala

In 2001
Male Suicide : 33935 	Female Suicide : 13925
In 2002
Male Suicide : 35825 	Female Suicide : 13225
In 2003
Male Suicide : 34675 	Female Suicide : 12515
In 2004
Male Suicide : 32990 	Female Suicide : 12275
In 2005
Male Suicide : 34150 	Female Suicide : 12070
In 2006
Male Suicide : 32915 	Female Suicide : 12215
In 2007
Male Suicide : 32940 	Female Suicide : 11870
In 2008
Male Suicide : 30650 	Female Suicide : 12195
In 2009
Male Suicide : 31610 	Female Suicide : 12165
In 2010
Male Suicide : 31730 	Female Suicide : 11200
In 2011
Male Suicide : 30328 	Female Suicide : 11093
In 2012
Male Suicide : 32045 	Female Suicide : 10405


In Lakshadweep

In 2001
Male Suicide : 0 	Female Suicide : 0
In 2002
Male Suicide : 0 	Female Suicide : 0
In 2003
Male Suicide : 5 	Female Suicide : 5
In 2004
Male Suicide : 0 	Female Suicide : 0
In 2005
Male Suicide : 0 	Female Suicide : 0
In 2006
Male Suicide : 5 	Female Suicide : 5
In 2007
Male Suicide : 5 	Female Suicide : 10
In 2008
Male Suicide : 0 	Female Suicide : 0
In 2009
Male Suicide : 0 	Female Suicide : 5
In 2010
Male Suicide : 0 	Female Suicide : 5
In 2011
Male Suicide : 0 	Female Suicide : 0
In 2012
Male Suicide : 5 	Female Suicide : 0


In Madhya Pradesh

In 2001
Male Suicide : 17680 	Female Suicide : 16620
In 2002
Male Suicide : 17895 	Female Suicide : 16600
In 2003
Male Suicide : 17690 	Female Suicide : 16120
In 2004
Male Suicide : 18170 	Female Suicide : 15805
In 2005
Male Suicide : 14255 	Female Suicide : 12985
In 2006
Male Suicide : 17515 	Female Suicide : 14660
In 2007
Male Suicide : 17350 	Female Suicide : 14295
In 2008
Male Suicide : 21825 	Female Suicide : 16320
In 2009
Male Suicide : 25500 	Female Suicide : 20065
In 2010
Male Suicide : 25435 	Female Suicide : 19580
In 2011
Male Suicide : 26200 	Female Suicide : 20095
In 2012
Male Suicide : 28870 	Female Suicide : 20005


In Maharashtra

In 2001
Male Suicide : 46690 	Female Suicide : 26400
In 2002
Male Suicide : 47235 	Female Suicide : 25410
In 2003
Male Suicide : 49050 	Female Suicide : 24750
In 2004
Male Suicide : 49515 	Female Suicide : 24130
In 2005
Male Suicide : 48015 	Female Suicide : 24115
In 2006
Male Suicide : 52550 	Female Suicide : 24920
In 2007
Male Suicide : 52100 	Female Suicide : 23820
In 2008
Male Suicide : 49445 	Female Suicide : 22425
In 2009
Male Suicide : 48925 	Female Suicide : 22575
In 2010
Male Suicide : 54290 	Female Suicide : 25290
In 2011
Male Suicide : 54435 	Female Suicide : 25300
In 2012
Male Suicide : 56520 	Female Suicide : 24040


In Manipur

In 2001
Male Suicide : 120 	Female Suicide : 85
In 2002
Male Suicide : 150 	Female Suicide : 45
In 2003
Male Suicide : 105 	Female Suicide : 25
In 2004
Male Suicide : 159 	Female Suicide : 45
In 2005
Male Suicide : 114 	Female Suicide : 20
In 2006
Male Suicide : 120 	Female Suicide : 60
In 2007
Male Suicide : 140 	Female Suicide : 55
In 2008
Male Suicide : 115 	Female Suicide : 55
In 2009
Male Suicide : 90 	Female Suicide : 44
In 2010
Male Suicide : 120 	Female Suicide : 65
In 2011
Male Suicide : 90 	Female Suicide : 75
In 2012
Male Suicide : 115 	Female Suicide : 90


In Meghalaya

In 2001
Male Suicide : 345 	Female Suicide : 90
In 2002
Male Suicide : 242 	Female Suicide : 90
In 2003
Male Suicide : 160 	Female Suicide : 45
In 2004
Male Suicide : 195 	Female Suicide : 80
In 2005
Male Suicide : 250 	Female Suicide : 105
In 2006
Male Suicide : 344 	Female Suicide : 115
In 2007
Male Suicide : 300 	Female Suicide : 135
In 2008
Male Suicide : 285 	Female Suicide : 139
In 2009
Male Suicide : 335 	Female Suicide : 222
In 2010
Male Suicide : 399 	Female Suicide : 138
In 2011
Male Suicide : 552 	Female Suicide : 209
In 2012
Male Suicide : 450 	Female Suicide : 190


In Mizoram

In 2001
Male Suicide : 230 	Female Suicide : 40
In 2002
Male Suicide : 280 	Female Suicide : 50
In 2003
Male Suicide : 205 	Female Suicide : 55
In 2004
Male Suicide : 265 	Female Suicide : 35
In 2005
Male Suicide : 235 	Female Suicide : 40
In 2006
Male Suicide : 298 	Female Suicide : 50
In 2007
Male Suicide : 110 	Female Suicide : 30
In 2008
Male Suicide : 175 	Female Suicide : 30
In 2009
Male Suicide : 304 	Female Suicide : 35
In 2010
Male Suicide : 335 	Female Suicide : 45
In 2011
Male Suicide : 385 	Female Suicide : 65
In 2012
Male Suicide : 777 	Female Suicide : 80


In Nagaland

In 2001
Male Suicide : 125 	Female Suicide : 75
In 2002
Male Suicide : 95 	Female Suicide : 40
In 2003
Male Suicide : 84 	Female Suicide : 25
In 2004
Male Suicide : 125 	Female Suicide : 30
In 2005
Male Suicide : 105 	Female Suicide : 30
In 2006
Male Suicide : 95 	Female Suicide : 45
In 2007
Male Suicide : 82 	Female Suicide : 34
In 2008
Male Suicide : 160 	Female Suicide : 50
In 2009
Male Suicide : 124 	Female Suicide : 29
In 2010
Male Suicide : 55 	Female Suicide : 5
In 2011
Male Suicide : 125 	Female Suicide : 40
In 2012
Male Suicide : 120 	Female Suicide : 30


In Odisha

In 2001
Male Suicide : 10439 	Female Suicide : 9815
In 2002
Male Suicide : 13155 	Female Suicide : 8785
In 2003
Male Suicide : 13700 	Female Suicide : 8400
In 2004
Male Suicide : 12720 	Female Suicide : 8355
In 2005
Male Suicide : 12770 	Female Suicide : 8270
In 2006
Male Suicide : 11865 	Female Suicide : 8460
In 2007
Male Suicide : 12440 	Female Suicide : 9100
In 2008
Male Suicide : 15775 	Female Suicide : 8745
In 2009
Male Suicide : 12835 	Female Suicide : 8990
In 2010
Male Suicide : 12150 	Female Suicide : 9125
In 2011
Male Suicide : 15300 	Female Suicide : 10905
In 2012
Male Suicide : 14480 	Female Suicide : 10655


In Puducherry

In 2001
Male Suicide : 1615 	Female Suicide : 1030
In 2002
Male Suicide : 2050 	Female Suicide : 785
In 2003
Male Suicide : 1940 	Female Suicide : 970
In 2004
Male Suicide : 1690 	Female Suicide : 1004
In 2005
Male Suicide : 1700 	Female Suicide : 990
In 2006
Male Suicide : 1745 	Female Suicide : 885
In 2007
Male Suicide : 1595 	Female Suicide : 990
In 2008
Male Suicide : 1670 	Female Suicide : 865
In 2009
Male Suicide : 1630 	Female Suicide : 960
In 2010
Male Suicide : 1665 	Female Suicide : 875
In 2011
Male Suicide : 1980 	Female Suicide : 805
In 2012
Male Suicide : 1860 	Female Suicide : 845


In Punjab

In 2001
Male Suicide : 1980 	Female Suicide : 1260
In 2002
Male Suicide : 1985 	Female Suicide : 550
In 2003
Male Suicide : 2530 	Female Suicide : 625
In 2004
Male Suicide : 2580 	Female Suicide : 645
In 2005
Male Suicide : 2410 	Female Suicide : 530
In 2006
Male Suicide : 3050 	Female Suicide : 810
In 2007
Male Suicide : 3160 	Female Suicide : 1075
In 2008
Male Suicide : 3215 	Female Suicide : 1130
In 2009
Male Suicide : 3175 	Female Suicide : 1060
In 2010
Male Suicide : 3595 	Female Suicide : 1005
In 2011
Male Suicide : 3775 	Female Suicide : 1055
In 2012
Male Suicide : 3920 	Female Suicide : 1230


In Rajasthan

In 2001
Male Suicide : 9795 	Female Suicide : 6180
In 2002
Male Suicide : 10460 	Female Suicide : 5780
In 2003
Male Suicide : 11945 	Female Suicide : 6360
In 2004
Male Suicide : 12430 	Female Suicide : 6195
In 2005
Male Suicide : 14290 	Female Suicide : 6599
In 2006
Male Suicide : 14550 	Female Suicide : 6765
In 2007
Male Suicide : 15770 	Female Suicide : 6415
In 2008
Male Suicide : 18010 	Female Suicide : 7820
In 2009
Male Suicide : 17555 	Female Suicide : 7770
In 2010
Male Suicide : 16825 	Female Suicide : 7775
In 2011
Male Suicide : 15080 	Female Suicide : 6660
In 2012
Male Suicide : 16135 	Female Suicide : 7970


In Sikkim

In 2001
Male Suicide : 310 	Female Suicide : 160
In 2002
Male Suicide : 263 	Female Suicide : 120
In 2003
Male Suicide : 340 	Female Suicide : 185
In 2004
Male Suicide : 278 	Female Suicide : 210
In 2005
Male Suicide : 310 	Female Suicide : 235
In 2006
Male Suicide : 490 	Female Suicide : 235
In 2007
Male Suicide : 420 	Female Suicide : 190
In 2008
Male Suicide : 1080 	Female Suicide : 355
In 2009
Male Suicide : 610 	Female Suicide : 594
In 2010
Male Suicide : 1175 	Female Suicide : 225
In 2011
Male Suicide : 531 	Female Suicide : 385
In 2012
Male Suicide : 480 	Female Suicide : 425


In Tamil Nadu

In 2001
Male Suicide : 35640 	Female Suicide : 20810
In 2002
Male Suicide : 34915 	Female Suicide : 21219
In 2003
Male Suicide : 35770 	Female Suicide : 23590
In 2004
Male Suicide : 39730 	Female Suicide : 24465
In 2005
Male Suicide : 37535 	Female Suicide : 22845
In 2006
Male Suicide : 37545 	Female Suicide : 24360
In 2007
Male Suicide : 43435 	Female Suicide : 25620
In 2008
Male Suicide : 45215 	Female Suicide : 26910
In 2009
Male Suicide : 44511 	Female Suicide : 27321
In 2010
Male Suicide : 52760 	Female Suicide : 30045
In 2011
Male Suicide : 51410 	Female Suicide : 28405
In 2012
Male Suicide : 53740 	Female Suicide : 30895


In Total (All India)

In 2001
Male Suicide : 132628 	Female Suicide : 84384
In 2002
Male Suicide : 138664 	Female Suicide : 82170
In 2003
Male Suicide : 140442 	Female Suicide : 81260
In 2004
Male Suicide : 145302 	Female Suicide : 82092
In 2005
Male Suicide : 145832 	Female Suicide : 81996
In 2006
Male Suicide : 151404 	Female Suicide : 84820
In 2007
Male Suicide : 158590 	Female Suicide : 86684
In 2008
Male Suicide : 161088 	Female Suicide : 88946
In 2009
Male Suicide : 162942 	Female Suicide : 91360
In 2010
Male Suicide : 174360 	Female Suicide : 94838
In 2011
Male Suicide : 175678 	Female Suicide : 95492
In 2012
Male Suicide : 176906 	Female Suicide : 93984


In Total (States)

In 2001
Male Suicide : 130196 	Female Suicide : 82754
In 2002